# Generated by Django 3.0.5 on 2020-04-21 12:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dias', multiselectfield.db.fields.MultiSelectField(choices=[('Lunes', 'LUN'), ('Martes', 'MAR'), ('Miércoles', 'MIE'), ('Jueves', 'JUE'), ('Viernes', 'VIE'), ('Sábado', 'SAB'), ('Domingo', 'DOM')], max_length=52, verbose_name='Días')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('estado', models.BooleanField(verbose_name='¿Habilitada?')),
            ],
        ),
    ]
