# Generated by Django 3.0.5 on 2020-04-26 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0004_auto_20200422_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estudiantes_inscritos',
            field=models.ManyToManyField(related_name='get_inscritos', to=settings.AUTH_USER_MODEL, verbose_name='Inscritos'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
    ]
