# Generated by Django 3.0.5 on 2020-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_auto_20200426_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='¿Habilitada?'),
        ),
    ]
