# Generated by Django 3.0.5 on 2020-04-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20200426_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
