# Generated by Django 3.0.5 on 2020-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0009_materia_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
