# Generated by Django 3.0.5 on 2020-04-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tipo', models.CharField(choices=[('Primer parcial', '1er Parcial'), ('Segundo parcial', '2do Parcial'), ('Exámen final', 'Ex. Final'), ('Control', 'Control'), ('Prácticos', 'Prácticos')], default='Primer Parcial', max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
