# Generated by Django 3.0.5 on 2020-04-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia'),
        ),
    ]
