# Generated by Django 3.0.5 on 2020-04-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_auto_20200425_2043'),
        ('calificaciones', '0002_calificacion_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='materias.Materia'),
        ),
    ]
