# Generated by Django 3.0.5 on 2020-04-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_auto_20200426_0243'),
        ('calificaciones', '0004_auto_20200425_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='materias.Materia'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
