# Generated by Django 3.0.5 on 2020-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_auto_20200426_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
